spring.application.name=cram_school_helper

# データベースへの接続URL
spring.datasource.url=jdbc:h2:mem:testdb

# データベースのドライバー
spring.datasource.driver-class-name=org.h2.Driver

# データベースへの接続時のユーザー名
spring.datasource.username=admin

# データベース接続時のパスワード
spring.datasource.password=

# H2データベースのコンソールの利用可能設定
# ブラウザからH2コンソールにアクセス可能
spring.h2.console.enabled=true

mybatis.mapper-locations=classpath*:/com/privates/magu1436/cram_school_helper/mapper/*.xml
logging.level.org.mybatis=DEBUG
logging.level.org.mybatis.spring=DEBUG

